name: CI Eleve

on:
  push:
    branches: [ main ]

env:
  CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
  RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
  RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
  TOKEN_EXPIRATION_TIME: ${{ secrets.TOKEN_EXPIRATION_TIME }}
  INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar Repo
      uses: actions/checkout@v4

    - name: Configuracao JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build com maven
      run: mvn -B package -DskipTests
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clonar Repo
      uses: actions/checkout@v4

    - name: Configuracao JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Testar com maven
      run: mvn test
  docker:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: codifica/eleve-backend:latest 
