name: CI Eleve

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL=jdbc: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
      TOKEN_EXPIRATION_TIME: ${{ secrets.TOKEN_EXPIRATION_TIME }}
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
    steps:
    - name: Clonar Repo
      uses: actions/checkout@v4

    - name: Configuracao JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build com maven
      run: mvn -B package -DskipTests
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clonar Repo
      uses: actions/checkout@v4

    - name: Configuracao JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Testar com maven
      run: mvn test