name: CI Eleve

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar Repo
      uses: actions/checkout@v4

    - name: Configuracao JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build com maven
      run: mvn -B package -DskipTests
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clonar Repo
      uses: actions/checkout@v4

    - name: Configuracao JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Testar com maven
      run: mvn test